package com.example.myapplication

val currencies = arrayOf(
    "Afghan afghani",
    "Albanian lek",
    "Algerian dinar",
    "Euro",
    "Angolan kwanza",
    "Eastern Caribbean dollar",
    "Argentine peso",
    "Armenian dram",
    "Australian dollar",
    "Euro",
    "manat",
    "Bahamian dollar",
    "Bahraini dinar",
    "Bangladeshi taka",
    "Barbados Dollar",
    "Belarusian ruble",
    "Euro",
    "Belize dollar",
    "West African CFA franc",
    "Bhutanese ngultrum",
    "Boliviano",
    "Bosnia-Herzegovina Convertible Marka",
    "Botswana pula",
    "Brazilian real",
    "Brunei dollar",
    "Bulgarian lev",
    "West African CFA franc",
    "Burundian franc",
    "Cape Verdean escudo",
    "Cambodian riel",
    "Central African CFA franc",
    "Canadian dollar",
    "Central African CFA franc",
    "Central African CFA franc",
    "Chilean peso",
    "Renminbi",
    "Colombian peso",
    "Comorian franc",
    "Congolese franc",
    "Costa Rican colón",
    "Croatian kuna",
    "Cuban peso",
    "Euro",
    "Czech koruna",
    "West African CFA franc",
    "Congolese franc",
    "Danish krone",
    "Djiboutian franc",
    "Eastern Caribbean dollar",
    "Dominican peso",
    "Egyptian pound",
    "Salvadoran colón",
    "United States Dollar",
    "Central African CFA franc",
    "Eritrean nakfa",
    "Euro",
    "Swazi lilangeni",
    "Ethiopian birr",
    "Fijian dollar",
    "Euro",
    "Euro",
    "Central African CFA franc",
    "Gambian dalasi",
    "Georgian lari",
    "Euro",
    "Ghanaian cedi",
    "Euro",
    "Eastern Caribbean dollar",
    "Guatemalan quetzal",
    "Guinean franc",
    "West African CFA franc",
    "Guyanese dollar",
    "Haitian gourde",
    "Euro",
    "Honduran lempira",
    "Hungarian forint",
    "Icelandic króna",
    "Indian rupee",
    "Indonesian rupiah",
    "Iranian rial",
    "Iraqi dinar",
    "Euro",
    "Euro",
    "Jamaican dollar",
    "Japanese yen",
    "Jordanian dinar",
    "Kazakhstani tenge",
    "Kenyan shilling",
    "Australian dollar",
    "Kuwaiti Dinar",
    "Kyrgyzstani som",
    "Lao kip",
    "Euro",
    "Lebanese pound",
    "Lesotho loti",
    "Liberian dollar",
    "Libyan dinar",
    "Swiss franc",
    "Euro",
    "Euro",
    "Malagasy ariary",
    "Malawian kwacha",
    "Malaysian ringgit",
    "Maldivian rufiyaa",
    "Moldovan leu",
    "West African CFA franc",
    "Euro",
    "Mongolian tögrög",
    "United States Dollar",
    "Mauritanian Ouguiya",
    "Mauritian rupee",
    "Mexican peso",
    "United States Dollar",
    "Euro",
    "Euro",
    "Moroccan dirham",
    "Mozambican metical",
    "Myanmar kyat",
    "Namibian dollar",
    "Australian dollar",
    "Nepalese rupee",
    "Euro",
    "New Zealand dollar",
    "Nicaraguan córdoba",
    "West African CFA franc",
    "Nigerian naira",
    "North Korean won",
    "Macedonian denar",
    "Norwegian krone",
    "Omani rial",
    "Pakistani Rupee",
    "United States Dollar",
    "Palestine pound",
    "Panamanian balboa",
    "Papua New Guinean kina",
    "Paraguayan guaraní",
    "Sol",
    "Philippine peso",
    "Polish zloty",
    "Euro",
    "Qatari Riyal",
    "Romanian leu",
    "Russian ruble",
    "Rwandan franc",
    "Eastern Caribbean dollar",
    "Eastern Caribbean dollar",
    "Samoan tālā",
    "Euro",
    "São Tomé and Príncipe dobra",
    "Saudi riyal",
    "West African CFA franc",
    "Serbian dinar",
    "Seychellois rupee",
    "Sierra Leonean leone",
    "Singapore dollar",
    "Euro",
    "Euro",
    "Solomon Islands dollar",
    "Somali shilling",
    "South African rand",
    "South Korean won",
    "South Sudanese pound",
    "Euro",
    "Sri Lankan rupee",
    "Eastern Caribbean dollar",
    "Sudanese pound",
    "Suriname Dollar",
    "Swedish krona",
    "Swiss franc",
    "Syrian pound",
    "Tajikistani somoni",
    "Tanzanian shilling",
    "Thai baht",
    "United States Dollar",
    "Trinidad and Tobago dollar",
    "West African CFA franc",
    "Tongan paʻanga",
    "Tunisian dinar",
    "Turkish lira",
    "Turkmenistani manat",
    "Australian Dollar",
    "Ugandan shilling",
    "Hryvnia",
    "United Arab Emirates dirham",
    "Pound sterling",
    "United States Dollar",
    "Peso Uruguayo",
    "Uzbekistani soʻm",
    "Vanuatu vatu",
    "Venezuelan bolívar",
    "Vietnamese dong",
    "Yemeni rial",
    "Zambian kwacha",
    "United States Dollar"
)